spring.application.name=lab2
server.port=8081
greeting-message=Hello from Spring Boot!

management.endpoints.web.exposure.include=info,health,metrics
management.info.env.enabled=true
info.app.name=lab2
info.app.description=Lab 2 - Spring Boot


#http://localhost:8081/actuator  -	lista endpoint-urilor disponibile
#http://localhost:8081/actuator/health
#http://localhost:8081/actuator/inf
#http://localhost:8081/actuator/metrics	 -  lista tuturor metricilor
#http://localhost:8081/actuator/metrics/jvm.memory.used	 -  memoria folosită acum
